### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by maxw2000** [GringoGuy/massdm#1]
hello,

i found an bug in the massdm bot.
when you do this in an discord with 8k+ members it will do it so fast that discord will block all the message.

`DMing Mies?//MC Teunplaysnl??
(node:10436) UnhandledPromiseRejectionWarning: DiscordAPIError: You are opening direct messages too fast.
    at item.request.gen.end (C:\Users\max\OneDrive\massdm\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
    at then (C:\Users\max\OneDrive\massdm\node_modules\snekfetch\src\index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:10436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)`

screenshot: https://imgur.com/a/zVYWeaM

**Comment by GringoGuy** [comment]
Should work now. However, I'm no longer giving support for this bot.

**Comment by BlazerCrafter** [comment]
i am getting same error help !
